BlogMvcApp2/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogMvcApp2.Models
{
    public class Post
    {
       
        public int userId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }

    }
}

BlogMvcApp2/Controllers/JSONExamplesController.cs
using BlogMvcApp2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace BlogMvcApp2.Controllers
{
    public class JSONExamplesController : Controller
    {
        // GET: JSONExamples 

        [HttpGet]
        public ActionResult Posts()
        {

            return View(GetPosts());
        }

        public ActionResult PostsGet()
        {
            return View();
        }


        [HttpGet]
        public JsonResult PostsGetjson()
        {
            List<Post> posts = new List<Post>();
            using (var client = new HttpClient())
            {
                var content = client.GetStringAsync("https://jsonplaceholder.typicode.com/posts").Result;
                posts = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Post>>(content);
            }
            return Json(posts, JsonRequestBehavior.AllowGet);
        }



        public List<Post> GetPosts()
        {
            List<Post> posts = new List<Post>();
            using (var client = new HttpClient())
            {
                var content = client.GetStringAsync("https://jsonplaceholder.typicode.com/posts").Result;
                posts = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Post>>(content);
            }
            return posts;
        }

        public ActionResult NewPosts()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewPosts(Post post)
        {
            using (var client = new HttpClient())
            {
                //Auth Token Gönderme
                //client.DefaultRequestHeaders.Add("Authorization", "Bearer " + "dssddsdadadasdasdad");
                // mmmmmm
                // Auth Basic
                //var authenticationBytes = Encoding.ASCII.GetBytes("YourUsername:YourPassword");
                //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
                //Convert.ToBase64String(authenticationBytes));


                var json = Newtonsoft.Json.JsonConvert.SerializeObject(post);

                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                var content = client.PostAsync("https://jsonplaceholder.typicode.com/posts", stringContent).Result;

                var reads = content.Content.ReadAsStringAsync().Result;
            }
            return View();


        }




        [HttpPost]
        public JsonResult NewPostsjson(Post post)
        {
            using (var client = new HttpClient())
            {
                //Auth Token Gönderme
                //client.DefaultRequestHeaders.Add("Authorization", "Bearer " + "dssddsdadadasdasdad");

                // Auth Basic
                //var authenticationBytes = Encoding.ASCII.GetBytes("YourUsername:YourPassword");
                //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
                //Convert.ToBase64String(authenticationBytes));


                var json = Newtonsoft.Json.JsonConvert.SerializeObject(post);

                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                var content = client.PostAsync("https://jsonplaceholder.typicode.com/posts", stringContent).Result;

                var reads = content.Content.ReadAsStringAsync().Result;
            }
            return Json(post, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Update(int Id)
        {
            var gelen = GetPosts().Where(p => p.id == Id).FirstOrDefault();
            return View(gelen);
        }

        [HttpPost]

        public ActionResult Update(Post post)
        {
            using (var client = new HttpClient())
            {
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(post);

                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                var content = client.PutAsync("https://jsonplaceholder.typicode.com/posts/" + post.id, stringContent).Result;

                var reads = content.Content.ReadAsStringAsync().Result;
            }


            return View();


        }


        // Auth Basic --
        //var authenticationBytes = Encoding.ASCII.GetBytes("YourUsername:YourPassword");
        //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
        //Convert.ToBase64String(authenticationBytes));

    }
}

BlogMvcApp2/Views/JSONExamples/NewPosts.cshtml
@model BlogMvcApp2.Models.Post

@{
    ViewBag.Title = "NewPosts";
}

<h2>NewPosts</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input value="Create" class="btn btn-default" id="btnForm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts
{
    <script src="~/Scripts/deneme.js"></script>

}

BlogMvcApp2/Views/JSONExamples/Posts.cshtml
@model IEnumerable<BlogMvcApp2.Models.Post>
@{
    ViewBag.Title = "Posts";
}

<h2>Posts</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th> Sıra No</th>
            <th> Detay </th>
            <th scope="col"> User Id</th>
            <th scope="col">Id</th> 
            <th scope="col">Title</th>
            <th scope="col">Body</th>
        </tr>
    </thead>
    <tbody>


        @{int sayi = 0; }

        @foreach (var item in Model)
        {

        <tr>
            <td> @sayi </td>

            <td> @Html.ActionLink(" Detay", "Update", "JSONExamples", new { id = item.id }, null )</td>
            <td> @item.userId </td>
            <td>@item.id</td>
            <td>@item.title</td>
            <td>@item.body</td>
        </tr>
            sayi++;
        }
            

    </tbody>

</table>

BlogMvcApp2/Views/JSONExamples/PostsGet.cshtml
<h2>PostGet</h2>

<table class="table table-hover"  id="myTable">
    <thead>
        <tr>
            @*<th> Sıra No</th>*@
            @*<th> Detay </th>*@
            <th scope="col"> User Id</th>
            <th scope="col">Id</th>
            <th scope="col">Title</th>
            <th scope="col">Body</th>
        </tr>
    </thead>
    <tbody>


        @*@{int sayi = 0; }

            @foreach (var item in Model)
            {

                <tr>
                    <td> orn3k :)</td>

                </tr>
                sayi++;
            }*@


    </tbody>

</table>


@section scripts
{
    <script src="~/Scripts/deneme.js"></script>

}

BlogMvcApp2/Views/JSONExamples/Update.cshtml
@model BlogMvcApp2.Models.Post

@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>


@using (Html.BeginForm("Update", "JSONExamples", FormMethod.Post))
{
    @Html.AntiForgeryToken()
  

<div class="form-horizontal">
    <h4>Post</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } } )
            
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.userId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userId, new { htmlAttributes = new { @class = "form-control"} })
           
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control"} })
           
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.body, new { htmlAttributes = new { @class = "form-control"} })
          
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}